Music album milestone 3 : add and list all genres
levy002/catalog_of_things pull request #48
Opened 2022-06-29 14:23 UTC by Nemwel-Boniface

## Hello :wave: 
In this milestone I was able to:

- [x] Create a genre album
- [x] Save a genre album
- [x] List all available genre albums
- [x] Check and resolve all found offenses
- [x] Save to JSON files
- [x] Retrieve and display from JSON files

Thank you for reviewing my project :pray:

2022-06-29 20:11 UTC, levy002 requested changes
## Hi @Nemwel-Boniface , 

Good job so far!

## Highlight!
- Good feature branch name ✔️ 
- No linter errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

2022-06-30 04:37 UTC, Nemwel-Boniface commented on musicAlbum/music_controller.rb
>    end
Thank you Levy for this suggestion, let me effect it immediately.

2022-06-30 04:37 UTC, Nemwel-Boniface commented on musicAlbum/genre_controller.rb
> +  end
Thank you Levy for this suggestion, let me effect it immediately.

2022-06-30 04:53 UTC, Nemwel-Boniface commented
Hello, @levy002  I have made the requested changes and now it is working exactly as expected. I will merge the PR.

2022-06-30 04:53 UTC, merged